version: "3.8"

services:
  mongo:
    image: mongo
    container_name: board-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: board-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo:27017/board
    restart: always

  frontend:
    build: ./frontend
    container_name: board-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
